/*
 * generated by Xtext
 */
package gaml.compiler.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class GamlProposalProvider extends AbstractGamlProposalProvider {
}
